services:
  db:
    image: postgres:15-alpine
    container_name: medinexus_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: medinexus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medinexus_network

  ai-engine:
    build:
      context: ./backend
      dockerfile: ./ai-engine/Dockerfile
    container_name: medinexus_ai_engine
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    networks:
      - medinexus_network

  backend:
    build: ./backend
    container_name: medinexus_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:securepassword123@db:5432/medinexus
      - AI_ENGINE_URL=http://ai-engine:8080
    depends_on:
      - db
    networks:
      - medinexus_network

  frontend:
    build: ./frontend
    container_name: medinexus_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - medinexus_network

  admin_frontend:
    build: ./frontend/admins-portal
    container_name: medinexus-ai-admin_frontend-1
    command: sh -c "rm -rf node_modules package-lock.json && npm install && npm run dev"
    ports:
      - "3001:3001"
    volumes:
      - ./frontend/admins-portal:/app
      - admins_node_modules:/app/node_modules

volumes:
  postgres_data:
  admins_node_modules:

networks:
  medinexus_network:
    driver: bridge
