import { Patient, Specialist, Appointment, NotificationItem } from './types';

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'p1',
    name: 'Aarav Mehta',
    mrn: 'ABHA-MN-9921',
    dept: 'Cardiology',
    age: 41,
    gender: 'Male',
    blood: 'O+',
    priority: 'HIGH',
    status: 'WAITING',
    lastVisit: 'Oct 10, 2026',
    nextAppointment: 'Tomorrow at 10:00 AM (OPD Suite 304)',
    allergies: 'Penicillin (severe anaphylaxis), Sulfa compounds',
    meds: 'Lisinopril 10mg daily, Metoprolol Tartrate 25mg BID, Aspirin 81mg daily',
    history: 'Previous myocardial ischemia workup (2024), drug-eluting stent placement (LAD, 2022). Essential hypertension.',
    reason: 'Persistent chest tightness upon moderate exertion radiating towards left shoulder over past 72 hours. Patient reports palpitations at night.',
    recommendation: 'Perform 12-lead resting ECG and STAT Troponin-I panel. Review medication compliance regarding beta-blocker timing. Consider stress echocardiography if troponin remains negative.',
    heartRate: '74 bpm'
  },
  {
    id: 'p2',
    name: 'Rahul Sharma',
    mrn: 'ABHA-MN-1045',
    dept: 'Cardiology',
    age: 53,
    gender: 'Male',
    blood: 'B+',
    priority: 'HIGH',
    status: 'WAITING',
    lastVisit: 'Sep 28, 2026',
    nextAppointment: 'Today at 02:30 PM (Suite 102)',
    allergies: 'Aspirin (dyspepsia/bronchospasm)',
    meds: 'Clopidogrel 75mg daily, Atorvastatin 40mg at bedtime, Ramipril 5mg',
    history: 'Coronary artery bypass graft (CABG x2, 2021). Type 2 Diabetes mellitus managed with diet and metformin.',
    reason: 'Uncontrolled nocturnal dyspnea and bilateral ankle edema progression over 5 days.',
    recommendation: 'Assess BNP levels, order bedside lung ultrasound for pulmonary congestion, evaluate loop diuretic dose escalation.',
    heartRate: '118 bpm'
  },
  {
    id: 'p3',
    name: 'Sunita Sen',
    mrn: 'ABHA-MN-2408',
    dept: 'Cardiology',
    age: 36,
    gender: 'Female',
    blood: 'A+',
    priority: 'NORMAL',
    status: 'COMPLETED',
    lastVisit: 'Nov 02, 2026',
    nextAppointment: 'Dec 15, 2026 at 11:15 AM',
    allergies: 'No known drug allergies (NKDA)',
    meds: 'Levothyroxine 50mcg, Propranolol 10mg PRN for palpitations',
    history: 'Supraventricular tachycardia (ablation in 2023). Hashimoto thyroiditis.',
    reason: 'Routine post-ablation Holter monitor follow-up. Reports feeling well without recent syncopal episodes.',
    recommendation: 'Holter shows 99% normal sinus rhythm with rare PACs. Continue current levothyroxine dosage with routine TSH in 6 months.',
    heartRate: '68 bpm'
  },
  {
    id: 'p4',
    name: 'Marcus Khan',
    mrn: 'MN-7712',
    dept: 'Cardiology',
    age: 62,
    gender: 'Male',
    blood: 'AB-',
    priority: 'HIGH',
    status: 'WAITING',
    lastVisit: 'Aug 19, 2026',
    nextAppointment: 'Today at 04:00 PM (Clinic 210)',
    allergies: 'ACE inhibitors (chronic dry cough), Codeine',
    meds: 'Losartan 50mg, Amlodipine 5mg, Rosuvastatin 20mg',
    history: 'Paroxysmal Atrial Fibrillation on Apixaban, moderate aortic sclerosis.',
    reason: 'Smartwatch flagged 3 distinct atrial fibrillation episodes during sleep exceeding 125 bpm.',
    recommendation: 'Confirm rhythm via telemetry, verify Apixaban adherence, evaluate rate control adjustment with Dr. Gupta.',
    heartRate: '92 bpm'
  },
  {
    id: 'p5',
    name: 'Eleanor Vance',
    mrn: 'MN-3390',
    dept: 'Cardiology',
    age: 70,
    gender: 'Female',
    blood: 'O-',
    priority: 'NORMAL',
    status: 'COMPLETED',
    lastVisit: 'Oct 24, 2026',
    nextAppointment: 'Jan 08, 2027 at 09:30 AM',
    allergies: 'Latex, Ciprofloxacin',
    meds: 'Metoprolol Succinate 50mg, Furosemide 20mg, Potassium Chloride 10mEq',
    history: 'Compensated heart failure with preserved ejection fraction (HFpEF, EF 52%). Osteoporosis.',
    reason: 'Monthly fluid balance checkpoint and metabolic panel review.',
    recommendation: 'Electrolytes and eGFR stable. Continue stable diuretic dosing. Advise low sodium intake adherence.',
    heartRate: '72 bpm'
  },
  {
    id: 'p6',
    name: 'Priya Sharma',
    mrn: 'MN-8840',
    dept: 'Cardiology',
    age: 29,
    gender: 'Female',
    blood: 'A-',
    priority: 'NORMAL',
    status: 'WAITING',
    lastVisit: 'Oct 30, 2026',
    nextAppointment: 'Tomorrow at 11:30 AM (Suite 102)',
    allergies: 'Ibuprofen (urticaria)',
    meds: 'Oral contraceptive, Vitamin D3 2000 IU daily',
    history: 'Inappropriate sinus tachycardia, postural orthostatic tachycardia syndrome (POTS) evaluation.',
    reason: 'Tilt table testing follow-up and orthostatic intolerance symptom survey.',
    recommendation: 'Hydration and electrolyte loading protocol recommended. Compression garments 20-30 mmHg prescribed.',
    heartRate: '86 bpm'
  }
];

export const SPECIALISTS: Specialist[] = [
  {
    id: 'neurology',
    name: 'Dr. Ananya Roy, MD, DM',
    specialty: 'Neurology & Clinical Triage',
    title: 'Neurovascular Specialist • 16 yrs exp.',
    facility: 'Max Super Speciality Hospital, Gurgaon',
    wing: 'Neurology Tower',
    room: 'Room 402',
    rating: '4.95',
    reviews: '(142 verified reviews)',
    copay: '₹1,000 Fee',
    copayAmount: '₹1000.00',
    fee: '₹1,000 Fee',
    earliest: 'Tomorrow, Oct 25',
    photo: 'https://images.unsplash.com/photo-1594824813511-1376d2994eb6?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'cardiology',
    name: 'Dr. Shiv Gupta, MD, FACC',
    specialty: 'Cardiology & Electrophysiology',
    title: 'Senior Cardiologist • 19 yrs exp.',
    facility: 'Apollo Hospitals, New Delhi',
    wing: 'Cardiology Wing',
    room: 'Ste 4B',
    rating: '4.9',
    reviews: '(180+ verified reviews)',
    copay: '₹800 Fee',
    copayAmount: '₹800.00',
    fee: '₹800 Fee',
    earliest: 'Tomorrow, Oct 25',
    photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDE5t9YjgeORyB6vFfCDeIIIaRa432s4mT_3YjpsWo-llKbwGnOLc8BKHDHcqmz5GpOlyJOVFrtuKF5I43P6I7eZZ2uW_BDtLh-A8GN8ZiefSEeSBGN-8ZWibU6JNb0cN76L92nwC5-8twN7TBjX-4GNbXUWCA3psZCFkMY8kAtsadai5vRAwpVRf9INwyO7cSeY9EE8BXPQIDdJd4ajy3WT9SpCfJeFylNWXlkFd86jBdEpw12yohFgg'
  },
  {
    id: 'telehealth',
    name: 'Dr. Sunita Deshmukh, MD',
    specialty: 'Preventative Care & Telehealth',
    title: 'Lead Tele-Internist • 12 yrs exp.',
    facility: 'Fortis Healthcare Tele-Clinic',
    wing: 'Ambulatory Care Wing',
    room: 'Room 210',
    rating: '4.95',
    reviews: '(215 verified reviews)',
    copay: '₹500 Fee (Star Health Covered)',
    copayAmount: '₹500.00',
    fee: '₹500 Fee',
    earliest: 'Today, Oct 24',
    photo: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'primary-care',
    name: 'Dr. Rajesh Iyer, MD',
    specialty: 'Primary Care & Internal Medicine',
    title: 'Lead Internal Medicine • 14 yrs exp.',
    facility: 'Manipal Hospital, Bengaluru',
    wing: 'OPD Block',
    room: 'Suite 112',
    rating: '4.8',
    reviews: '(240+ verified reviews)',
    copay: '₹600 Fee',
    copayAmount: '₹600.00',
    fee: '₹600 Fee',
    earliest: 'Today, Oct 24',
    photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'orthopedics',
    name: 'Dr. Vikram Malhotra, MS',
    specialty: 'Orthopedics & Sports Medicine',
    title: 'Orthopedic & Joint Surgeon • 21 yrs exp.',
    facility: 'BLK-Max Super Speciality Hospital',
    wing: 'Orthopedics Wing',
    room: 'Room 108',
    rating: '4.9',
    reviews: '(195 verified reviews)',
    copay: '₹1,200 Fee',
    copayAmount: '₹1200.00',
    fee: '₹1,200 Fee',
    earliest: 'Wednesday, Oct 26',
    photo: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 'endocrinology',
    name: 'Dr. Kavita Reddy, MD, DM',
    specialty: 'Endocrinology & Diagnostics',
    title: 'Metabolic Endocrinology • 15 yrs exp.',
    facility: 'Medanta - The Medicity, Gurugram',
    wing: 'Diagnostic Center',
    room: 'Suite 205',
    rating: '4.88',
    reviews: '(164 verified reviews)',
    copay: '₹900 Fee',
    copayAmount: '₹900.00',
    fee: '₹900 Fee',
    earliest: 'Thursday, Oct 27',
    photo: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80'
  }
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-patient-upcoming-1',
    bookingId: '#MNX-IN-9021',
    name: 'Ananya Sharma',
    ageGender: '29y • Female',
    mrn: 'MN-PT-4091',
    department: 'Cardiology',
    modality: 'In-Person OPD (Apollo Hospital)',
    time: '10:30 AM',
    dateLabel: 'Tomorrow',
    date: 'Tomorrow, Oct 25, 2026',
    status: 'UPCOMING',
    reason: 'Quarterly cardiac review & 12-lead ECG evaluation',
    initials: 'AS',
    bgColor: 'bg-primary text-white',
    doctor: {
      name: 'Dr. Shiv Gupta, MD, FACC',
      specialty: 'Cardiology & Electrophysiology',
      facility: 'Apollo Hospitals, New Delhi',
      hospitalAffiliation: 'Apollo Hospitals • OPD Suite 304',
      photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDE5t9YjgeORyB6vFfCDeIIIaRa432s4mT_3YjpsWo-llKbwGnOLc8BKHDHcqmz5GpOlyJOVFrtuKF5I43P6I7eZZ2uW_BDtLh-A8GN8ZiefSEeSBGN-8ZWibU6JNb0cN76L92nwC5-8twN7TBjX-4GNbXUWCA3psZCFkMY8kAtsadai5vRAwpVRf9INwyO7cSeY9EE8BXPQIDdJd4ajy3WT9SpCfJeFylNWXlkFd86jBdEpw12yohFgg',
      copay: '₹800 Fee'
    } as any,
    coverage: { copay: '₹800.00' }
  },
  {
    id: 'apt-patient-past-1',
    bookingId: '#MNX-IN-7812',
    name: 'Ananya Sharma',
    ageGender: '29y • Female',
    mrn: 'MN-PT-4091',
    department: 'Neurology',
    modality: 'Secure Teleconsult',
    time: '03:00 PM',
    dateLabel: 'Sep 12',
    date: 'Sep 12, 2026',
    status: 'COMPLETED',
    reason: 'Migraine evaluation & aura symptom consultation',
    initials: 'AS',
    bgColor: 'bg-surface-container-high text-on-surface',
    doctor: {
      name: 'Dr. Eleanor Rigby, MD',
      specialty: 'Neurology & Clinical Triage',
      facility: 'Max Super Speciality Hospital, Gurgaon',
      hospitalAffiliation: 'Max Super Speciality Hospital',
      photo: 'https://images.unsplash.com/photo-1594824813511-1376d2994eb6?auto=format&fit=crop&w=400&q=80',
      copay: '₹1,000 Fee'
    } as any,
    coverage: { copay: '₹1,000.00' }
  },
  {
    id: 'apt-1',
    bookingId: '#MNX-89241',
    name: 'Eleanor Vance',
    ageGender: 'Female, 58 yrs',
    mrn: 'MRN-902381',
    department: 'Cardiology',
    modality: 'In-Person Room 304',
    time: '09:30 AM',
    dateLabel: 'Today',
    date: 'Today, Oct 24, 2026',
    status: 'TODAY',
    reason: 'Persistent chest discomfort & exertion shortness of breath',
    initials: 'EV',
    bgColor: 'bg-[#258360] text-white',
    doctor: {
      name: 'Dr. Shiv Gupta, MD, FACC',
      specialty: 'Cardiology & Electrophysiology',
      facility: 'City Care General Hospital',
      hospitalAffiliation: 'City Care General Hospital • Room 304, Ste 4B',
      photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDE5t9YjgeORyB6vFfCDeIIIaRa432s4mT_3YjpsWo-llKbwGnOLc8BKHDHcqmz5GpOlyJOVFrtuKF5I43P6I7eZZ2uW_BDtLh-A8GN8ZiefSEeSBGN-8ZWibU6JNb0cN76L92nwC5-8twN7TBjX-4GNbXUWCA3psZCFkMY8kAtsadai5vRAwpVRf9INwyO7cSeY9EE8BXPQIDdJd4ajy3WT9SpCfJeFylNWXlkFd86jBdEpw12yohFgg',
      copay: '$20 Copay'
    } as any,
    coverage: { copay: '$20.00' }
  },
  {
    id: 'apt-2',
    bookingId: '#MNX-89242',
    name: 'Marcus Sterling',
    ageGender: 'Male, 46 yrs',
    mrn: 'MRN-849102',
    department: 'Cardiology',
    modality: 'In-Person Room 302',
    time: '11:00 AM',
    dateLabel: 'Today',
    date: 'Today, Oct 24, 2026',
    status: 'TODAY',
    reason: 'Hypertension regimen titration and post-stress echo evaluation',
    initials: 'MS',
    bgColor: 'bg-[#79564b] text-white',
    doctor: {
      name: 'Dr. Shiv Gupta, MD, FACC',
      specialty: 'Cardiology & Electrophysiology',
      facility: 'City Care General Hospital',
      hospitalAffiliation: 'City Care General Hospital • Room 304, Ste 4B',
      photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDE5t9YjgeORyB6vFfCDeIIIaRa432s4mT_3YjpsWo-llKbwGnOLc8BKHDHcqmz5GpOlyJOVFrtuKF5I43P6I7eZZ2uW_BDtLh-A8GN8ZiefSEeSBGN-8ZWibU6JNb0cN76L92nwC5-8twN7TBjX-4GNbXUWCA3psZCFkMY8kAtsadai5vRAwpVRf9INwyO7cSeY9EE8BXPQIDdJd4ajy3WT9SpCfJeFylNWXlkFd86jBdEpw12yohFgg',
      copay: '$20 Copay'
    } as any,
    coverage: { copay: '$20.00' }
  },
  {
    id: 'apt-3',
    bookingId: '#MNX-89243',
    name: 'Sophia Castillo',
    ageGender: 'Female, 34 yrs',
    mrn: 'MRN-431890',
    department: 'Cardiology',
    modality: 'In-Person Room 304',
    time: '02:15 PM',
    dateLabel: 'Today',
    date: 'Today, Oct 24, 2026',
    status: 'TODAY',
    reason: 'Palpitations post-viral episode with documented sinus tachycardia',
    initials: 'SC',
    bgColor: 'bg-[#b15b5a] text-white',
    doctor: {
      name: 'Dr. Shiv Gupta, MD, FACC',
      specialty: 'Cardiology & Electrophysiology',
      photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDE5t9YjgeORyB6vFfCDeIIIaRa432s4mT_3YjpsWo-llKbwGnOLc8BKHDHcqmz5GpOlyJOVFrtuKF5I43P6I7eZZ2uW_BDtLh-A8GN8ZiefSEeSBGN-8ZWibU6JNb0cN76L92nwC5-8twN7TBjX-4GNbXUWCA3psZCFkMY8kAtsadai5vRAwpVRf9INwyO7cSeY9EE8BXPQIDdJd4ajy3WT9SpCfJeFylNWXlkFd86jBdEpw12yohFgg',
      copay: '$20 Copay'
    } as any,
    coverage: { copay: '$20.00' }
  },
  {
    id: 'apt-4',
    bookingId: '#MNX-89244',
    name: 'Arthur Pendelton',
    ageGender: 'Male, 71 yrs',
    mrn: 'MRN-110934',
    department: 'Cardiology',
    modality: 'In-Person Room 301',
    time: '04:00 PM',
    dateLabel: 'Today',
    date: 'Today, Oct 24, 2026',
    status: 'TODAY',
    reason: 'Aortic valve sclerosis checkup and anti-coagulation INR assessment',
    initials: 'AP',
    bgColor: 'bg-[#dfe4df] text-[#181d1a]',
    doctor: {
      name: 'Dr. Shiv Gupta, MD, FACC',
      specialty: 'Cardiology & Electrophysiology',
      photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDE5t9YjgeORyB6vFfCDeIIIaRa432s4mT_3YjpsWo-llKbwGnOLc8BKHDHcqmz5GpOlyJOVFrtuKF5I43P6I7eZZ2uW_BDtLh-A8GN8ZiefSEeSBGN-8ZWibU6JNb0cN76L92nwC5-8twN7TBjX-4GNbXUWCA3psZCFkMY8kAtsadai5vRAwpVRf9INwyO7cSeY9EE8BXPQIDdJd4ajy3WT9SpCfJeFylNWXlkFd86jBdEpw12yohFgg',
      copay: '$20 Copay'
    } as any,
    coverage: { copay: '$20.00' }
  },
  {
    id: 'apt-5',
    bookingId: '#MNX-89245',
    name: 'Devon Hayes',
    ageGender: 'Male, 52 yrs',
    mrn: 'MRN-773124',
    department: 'Cardiology',
    modality: 'In-Person Room 304',
    time: '09:00 AM',
    dateLabel: 'Mon 24',
    date: 'Monday, Oct 24, 2026',
    status: 'UPCOMING',
    reason: 'Post-CABG recovery checkup and exercise tolerance review',
    initials: 'DH',
    bgColor: 'bg-[#258360] text-white',
    doctor: {
      name: 'Dr. Shiv Gupta, MD, FACC',
      specialty: 'Cardiology & Electrophysiology',
      photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDE5t9YjgeORyB6vFfCDeIIIaRa432s4mT_3YjpsWo-llKbwGnOLc8BKHDHcqmz5GpOlyJOVFrtuKF5I43P6I7eZZ2uW_BDtLh-A8GN8ZiefSEeSBGN-8ZWibU6JNb0cN76L92nwC5-8twN7TBjX-4GNbXUWCA3psZCFkMY8kAtsadai5vRAwpVRf9INwyO7cSeY9EE8BXPQIDdJd4ajy3WT9SpCfJeFylNWXlkFd86jBdEpw12yohFgg',
      copay: '$20 Copay'
    } as any,
    coverage: { copay: '$20.00' }
  },
  {
    id: 'apt-6',
    bookingId: '#MNX-89246',
    name: 'Nadia Petrov',
    ageGender: 'Female, 41 yrs',
    mrn: 'MRN-339012',
    department: 'Cardiology',
    modality: 'In-Person Room 302',
    time: '10:30 AM',
    dateLabel: 'Mon 24',
    date: 'Monday, Oct 24, 2026',
    status: 'UPCOMING',
    reason: 'Follow-up for familial hyperlipidemia and PCSK9 inhibitor tolerance',
    initials: 'NP',
    bgColor: 'bg-[#79564b] text-white',
    doctor: {
      name: 'Dr. Shiv Gupta, MD, FACC',
      specialty: 'Cardiology & Electrophysiology',
      photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDE5t9YjgeORyB6vFfCDeIIIaRa432s4mT_3YjpsWo-llKbwGnOLc8BKHDHcqmz5GpOlyJOVFrtuKF5I43P6I7eZZ2uW_BDtLh-A8GN8ZiefSEeSBGN-8ZWibU6JNb0cN76L92nwC5-8twN7TBjX-4GNbXUWCA3psZCFkMY8kAtsadai5vRAwpVRf9INwyO7cSeY9EE8BXPQIDdJd4ajy3WT9SpCfJeFylNWXlkFd86jBdEpw12yohFgg',
      copay: '$20 Copay'
    } as any,
    coverage: { copay: '$20.00' }
  },
  {
    id: 'apt-11',
    bookingId: '#MNX-89247',
    name: 'Benjamin Brooks',
    ageGender: 'Male, 61 yrs',
    mrn: 'MRN-991201',
    department: 'Cardiology',
    modality: 'In-Person Room 304',
    time: '08:00 AM',
    dateLabel: 'Today',
    date: 'Today, Oct 24, 2026',
    status: 'COMPLETED',
    reason: 'Coronary angiogram post-procedure follow-up',
    initials: 'BB',
    bgColor: 'bg-[#258360] text-white',
    doctor: {
      name: 'Dr. Shiv Gupta, MD, FACC',
      specialty: 'Cardiology & Electrophysiology',
      photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDE5t9YjgeORyB6vFfCDeIIIaRa432s4mT_3YjpsWo-llKbwGnOLc8BKHDHcqmz5GpOlyJOVFrtuKF5I43P6I7eZZ2uW_BDtLh-A8GN8ZiefSEeSBGN-8ZWibU6JNb0cN76L92nwC5-8twN7TBjX-4GNbXUWCA3psZCFkMY8kAtsadai5vRAwpVRf9INwyO7cSeY9EE8BXPQIDdJd4ajy3WT9SpCfJeFylNWXlkFd86jBdEpw12yohFgg',
      copay: '$20 Copay'
    } as any,
    coverage: { copay: '$20.00' }
  },
  {
    id: 'apt-16',
    bookingId: '#MNX-89248',
    name: 'Rebecca Thorne',
    ageGender: 'Female, 42 yrs',
    mrn: 'MRN-331094',
    department: 'Cardiology',
    modality: 'In-Person Room 304',
    time: 'Today',
    dateLabel: 'Today',
    date: 'Today, Oct 24, 2026',
    status: 'CANCELLED',
    reason: 'Patient rescheduled due to travel conflict',
    initials: 'RT',
    bgColor: 'bg-error-container text-on-error-container',
    doctor: {
      name: 'Dr. Shiv Gupta, MD, FACC',
      specialty: 'Cardiology & Electrophysiology',
      photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDE5t9YjgeORyB6vFfCDeIIIaRa432s4mT_3YjpsWo-llKbwGnOLc8BKHDHcqmz5GpOlyJOVFrtuKF5I43P6I7eZZ2uW_BDtLh-A8GN8ZiefSEeSBGN-8ZWibU6JNb0cN76L92nwC5-8twN7TBjX-4GNbXUWCA3psZCFkMY8kAtsadai5vRAwpVRf9INwyO7cSeY9EE8BXPQIDdJd4ajy3WT9SpCfJeFylNWXlkFd86jBdEpw12yohFgg',
      copay: '$20 Copay'
    } as any,
    coverage: { copay: '$20.00' }
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Appointment: Alex John',
    icon: 'timer',
    type: 'appointment',
    category: 'appointment',
    unread: true,
    timeAgo: '15m until start',
    summary: 'Alex John — Cardiology Follow-up. Checked in at Reception Desk B.',
    content: 'Patient has completed automated kiosk check-in and blood pressure screening (126/82 mmHg). Medical records from discharge have been attached to the appointment docket.'
  },
  {
    id: 'notif-2',
    title: 'AI Synthesis: Sarah Jenkins',
    icon: 'smart_toy',
    type: 'ai-summary',
    category: 'ai-summary',
    unread: true,
    timeAgo: '22m ago',
    summary: 'MediNexus AI has generated a 3-page longitudinal differential breakdown.',
    content: 'Cross-referenced 4 recent Holter summaries and biochemical markers. Recommended next step: Order Free T3/T4 panel and schedule 48-hr ambulatory telemetry.'
  },
  {
    id: 'notif-3',
    title: 'Diagnostic ECG: Eleanor Vance',
    icon: 'ecg_heart',
    type: 'consultation',
    category: 'consultation',
    unread: false,
    timeAgo: '1h ago',
    summary: 'Sinus rhythm confirmed with slight PR lengthening. Ready for sign-off.',
    content: 'Telemetry unit confirms stable ST segment with no hyperacute T waves. Signed digitally by Cardiology Fellow on duty.'
  },
  {
    id: 'notif-4',
    title: 'Triage Transfer Completed',
    icon: 'assignment_turned_in',
    type: 'alert-log',
    category: 'alert-log',
    unread: false,
    timeAgo: '2h ago',
    summary: 'Patient admitted to Acute Medical Unit under Dr. V. Sen.',
    content: 'Handover protocols signed off by Dr. V. Sen at 12:15 IST without incident.'
  }
];
